### PR TITLE
feat: add redshift query engine

### PR DESCRIPTION
**Pull request by Brooke-white**
Adds redshift query engine python packages. @czgu -- is the testing provided below and in #693 sufficient for providing this query engine as "tier 1"? if not, I'm more than happy to perform additional testing, just let me know what else you'd like to see :).

Testing

- confirmed querybook `make` executes successfully after adding `-r extra.txt` in `requirements/local.txt`

Testing Screenshots

- Language Specific Autocomplete supported for Amazon Redshift datatypes

Screen Shot 2021-11-15 at 12 51 07 PM
Screen Shot 2021-11-15 at 12 49 54 PM
Screen Shot 2021-12-15 at 1 11 45 PM

- Query execution 
Screen Shot 2021-11-15 at 11 49 21 AM

- Query Engine execution provides status in UI

Screen Shot 2021-12-15 at 1 09 07 PM

- Query Engine generates logs

Screen Shot 2021-12-15 at 1 09 44 PM

- Authentication via IAM is supported

localhost_10001_admin_query_engine_4_ (1)

- Federated Authentication via Identity Provider is supported

localhost_10001_admin_query_engine_2_ (1) (1)

### CODE REVIEW

**Comment by czgu** [comment]
Hi Brooke, can you add RedshiftQueryExecutor similar to SnowflakeQueryExecutor? We can use that for better fine tuned behaviors such as error parsing.

In addition, would it possible to use better forms for connection details instead of free form JSON? You can use StructFormField, checkout `presto_executor_template` in `PrestoQueryExecutor` to see the format.

In addition, just curious, would it be possible to get % progress for redshift? No worries if it doesn't provide that info

**Comment by Brooke-white** [comment]
Hi @czgu,

Thanks for taking a look at this so quickly :)

> can you add RedshiftQueryExecutor

I've added this in 30e27d8

>  would it possible to use better forms for connection details instead of free form JSON?

The sqlalchemy template is supported, I just opted to use free form JSON in the example for screenshot purposes as the connection URL was cut off pretty quickly since it's long. e.g. `redshift+redshift_connector://oktauser:oktapassword@:/dev?region=us-east-2&credentials_provider=OktaCredentialsProvider&idp_host=oktahost&app_id=myappid&preferred_role=arn:aws:iam::01223456789012:role/MyRole&db_user=awsuser&cluster_identifier=redshift-cluster-1` *additionally, passing `iam true` to connect_args as JSON.*

> would it be possible to get % progress for redshift?

AFAIK this is not possible at this time.

**Comment by czgu** [comment]
Sounds good, one last note: can you add this to `all_executors.py`?

**Comment by Brooke-white** [comment]
@czgu, I think I did so [here](https://github.com/pinterest/querybook/commit/30e27d83534ebd2f6457dcdc978d2a39fb825df3#diff-73e33c7050059032d8bc8af2ba54c7593b5cba422adad68e84f3e46269804aa2R20) in 30e27d8 -- or is there an additional change I need to make to `all_executors.py`?

**Review by czgu — APPROVED** [review]

**Comment by czgu** [comment]
oh no, that's all, sorry i missed it

**Comment by czgu** [comment]
@Brooke-white sorry actually 1 more change, can you remove redshift from lib/query_executor/executors/sqlalchemy.py?
we no long need a generic one give there is a custom redshift now

**Comment by Brooke-white** [comment]
> can you remove redshift from lib/query_executor/executors/sqlalchemy.py

sure @czgu, done in c09aff1 :)

**Comment by czgu** [comment]
merged, thanks for adding redshift!

**Pull request merged**
